[profile.default]
solc_version = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[profile.ci]
solc_version = "0.8.23"
via_ir = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"